window.EXPORT_DOC_PNG_SCRIPT = [
    "function dLPNG(idx) {",
    "    var cd = document.getElementById('card-' + idx);",
    "    if (!cd) return;",
    "    var items = JSON.parse(cd.getAttribute('data-json')),",
    "        keys = Object.keys(items),",
    "        cD = document.createElement('canvas').getContext('2d');",
    "    cD.font = 'bold 96px sans-serif';",
    "    var tw = {}, rh = [], h = 1760;",
    "    keys.forEach(function(k) {",
    "        var v = String(items[k]), w = [], w1 = v.split(' ');",
    "        w1.forEach(function(x) {",
    "            if (x.length > 38) {",
    "                for (var i = 0; i < x.length; i += 38) w.push(x.substr(i, 38));",
    "            } else w.push(x);",
    "        });",
    "        var ln = '', lns = [];",
    "        w.forEach(function(x, n) {",
    "            var tL = ln + x + ' ';",
    "            if (cD.measureText(tL).width > 2800 && n > 0) {",
    "                lns.push(ln);",
    "                ln = x + ' ';",
    "            } else ln = tL;",
    "        });",
    "        lns.push(ln);",
    "        tw[k] = lns;",
    "        var r = Math.max(280, lns.length * 146 + 133);",
    "        rh.push(r);",
    "        h += r;",
    "    });",
    "    var cvs = document.createElement('canvas');",
    "    cvs.width = 5120;",
    "    cvs.height = h;",
    "    var c = cvs.getContext('2d');",
    "    c.fillStyle = '#050505';",
    "    c.fillRect(0, 0, 5120, h);",
    "    c.fillStyle = '#111111';",
    "    c.strokeStyle = 'rgba(255,215,0,0.2)';",
    "    c.lineWidth = 16;",
    "    if (c.roundRect) {",
    "        c.beginPath();",
    "        c.roundRect(160, 160, 4800, h - 320, 96);",
    "        c.fill();",
    "        c.stroke();",
    "    } else {",
    "        c.fillRect(160, 160, 4800, h - 320);",
    "        c.strokeRect(160, 160, 4800, h - 320);",
    "    }",
    "    c.textAlign = 'center';",
    "    c.textBaseline = 'middle';",
    "    c.fillStyle = '#FFD700';",
    "    c.font = '560px sans-serif';",
    "    c.fillText(cd.dataset.title.replace(/&quot;/g, '\"'), 2560, 980);",
    "    c.textAlign = 'left';",
    "    var y = 1760;",
    "    keys.forEach(function(k, i) {",
    "        c.fillStyle = 'rgba(255,215,0,0.2)';",
    "        c.fillRect(320, y - 160, 4480, 8);",
    "        c.fillStyle = '#FFA500';",
    "        c.font = 'bold 96px sans-serif';",
    "        c.fillText(k, 320, y);",
    "        c.fillStyle = '#ffffff';",
    "        c.font = 'bold 96px sans-serif';",
    "        c.textAlign = 'right';",
    "        var ty = y;",
    "        tw[k].forEach(function(ln) {",
    "            c.fillText(ln.trim(), 4800, ty);",
    "            ty += 146;",
    "        });",
    "        c.textAlign = 'left';",
    "        y += rh[i];",
    "    });",
    "    var a = document.createElement('a');",
    "    a.href = cvs.toDataURL('image/png');",
    "    a.download = 'glyphlab_' + cd.dataset.basehex + '.png';",
    "    a.click();",
    "}"
].join("\n");

window.EXPORT_DOC_SCRIPT_CONTENT = [
    "function cpTxt(t, el) {",
    "    if (navigator.clipboard) { navigator.clipboard.writeText(t); }",
    "    var o = el.style.opacity;",
    "    el.style.opacity = 0.5;",
    "    setTimeout(function() { el.style.opacity = o; }, 200);",
    "}",
    "function tM(idx) {",
    "    document.querySelectorAll('.menu-dropdown').forEach(function(el) {",
    "        if (el.id !== 'm-' + idx) el.style.display = 'none';",
    "    });",
    "    var el = document.getElementById('m-' + idx);",
    "    if (el) el.style.display = el.style.display === 'flex' ? 'none' : 'flex';",
    "}",
    "document.addEventListener('click', function(e) {",
    "    if (!e.target.closest('.menu-btn') && !e.target.closest('.menu-dropdown')) {",
    "        document.querySelectorAll('.menu-dropdown').forEach(function(el) { el.style.display = 'none'; });",
    "    }",
    "});",
    "function dL(c, f, t) {",
    "    var b = new Blob([c], { type: t }), a = document.createElement('a');",
    "    a.href = URL.createObjectURL(b);",
    "    a.download = f;",
    "    a.click();",
    "}",
    "function groupData() {",
    "    var g = { SINGLE: {}, COMBINED: {} };",
    "    document.querySelectorAll('.card').forEach(function(c) {",
    "        var t = c.dataset.type, b = c.dataset.block;",
    "        if (!g[t]) g[t] = {};",
    "        if (!g[t][b]) g[t][b] = [];",
    "        g[t][b].push(JSON.parse(c.getAttribute('data-json')));",
    "    });",
    "    if (Object.keys(g.SINGLE || {}).length === 0) delete g.SINGLE;",
    "    if (Object.keys(g.COMBINED || {}).length === 0) delete g.COMBINED;",
    "    return g;",
    "}",
    "var isGlobalExporting = false;",
    "async function dLG(type) {",
    "    if (isGlobalExporting) { alert('Export running!'); return; }",
    "    isGlobalExporting = true;",
    "    var a = document.getElementById('glbProgCont'),",
    "        i = document.getElementById('glbProgBar'),",
    "        s = document.getElementById('glbProgTxt'),",
    "        l = document.getElementById('glbProgETA');",
    "    if (a) a.style.display = 'flex';",
    "    var cards = document.querySelectorAll('.card'), tl = cards.length;",
    "    if (tl === 0) { isGlobalExporting = false; if (a) a.style.display = 'none'; return; }",
    "    var g = groupData(), dBlobs = [], c = '', m = Date.now(), NL = String.fromCharCode(10);",
    "    if (type === 'json') {",
    "        c = '{' + NL;",
    "        var tKeys = Object.keys(g), itCtr = 0;",
    "        for (var tkIdx = 0; tkIdx < tKeys.length; tkIdx++) {",
    "            var t = tKeys[tkIdx];",
    "            c += '  \"' + t + '\": {' + NL;",
    "            var bKeys = Object.keys(g[t]);",
    "            for (var bkIdx = 0; bkIdx < bKeys.length; bkIdx++) {",
    "                var b = bKeys[bkIdx];",
    "                c += '    \"' + b + '\": [' + NL;",
    "                var items = g[t][b];",
    "                for (var k = 0; k < items.length; k++) {",
    "                    var strItem = JSON.stringify(items[k], null, 2).split(NL).map(function(line, idx) { return idx === 0 ? line : '      ' + line; }).join(NL);",
    "                    c += '      ' + strItem + (k < items.length - 1 ? ',' + NL : NL);",
    "                    itCtr++;",
    "                    if (itCtr % 100 === 0 || itCtr === tl) {",
    "                        dBlobs.push(new Blob([c], { type: 'application/json' }));",
    "                        c = '';",
    "                        var p = Math.floor(itCtr / tl * 100);",
    "                        if (i) i.style.width = p + '%';",
    "                        if (s) s.innerText = p + '%';",
    "                        if (l) {",
    "                            var e = Date.now() - m, n = Math.max(0, Math.floor(e / itCtr * (tl - itCtr) / 1000));",
    "                            l.innerText = n > 60 ? Math.floor(n / 60) + 'm ' + (n % 60) + 's remaining' : n + 's remaining';",
    "                        }",
    "                        await new Promise(function(r) { setTimeout(r, 0); });",
    "                    }",
    "                }",
    "                c += '    ]' + (bkIdx < bKeys.length - 1 ? ',' : '') + NL;",
    "            }",
    "            c += '  }' + (tkIdx < tKeys.length - 1 ? ',' : '') + NL;",
    "        }",
    "        c += '}';",
    "        if (c.trim().length > 2) dBlobs.push(new Blob([c], { type: 'application/json' }));",
    "    } else {",
    "        var itCtr = 0;",
    "        for (var t in g) {",
    "            for (var b in g[t]) {",
    "                c += NL + NL + '[ ' + t + ' - ' + b + ' ]' + NL;",
    "                c += '='.repeat(t.length + b.length + 7) + NL + NL;",
    "                var items = g[t][b];",
    "                for (var k = 0; k < items.length; k++) {",
    "                    var str = '=== ' + (items[k]['CHARACTER'] || items[k]['SYMBOL'] || '') + ' ===' + NL;",
    "                    for (var prop in items[k]) { str += prop + ': ' + items[k][prop] + NL; }",
    "                    c += str;",
    "                    itCtr++;",
    "                    if (itCtr % 100 === 0 || itCtr === tl) {",
    "                        dBlobs.push(new Blob([c], { type: 'text/plain' }));",
    "                        c = '';",
    "                        var p = Math.floor(itCtr / tl * 100);",
    "                        if (i) i.style.width = p + '%';",
    "                        if (s) s.innerText = p + '%';",
    "                        if (l) {",
    "                            var e = Date.now() - m, n = Math.max(0, Math.floor(e / itCtr * (tl - itCtr) / 1000));",
    "                            l.innerText = n > 60 ? Math.floor(n / 60) + 'm ' + (n % 60) + 's remaining' : n + 's remaining';",
    "                        }",
    "                        await new Promise(function(r) { setTimeout(r, 0); });",
    "                    }",
    "                }",
    "            }",
    "        }",
    "        if (c.trim().length > 0) dBlobs.push(new Blob([c.trim()], { type: 'text/plain' }));",
    "    }",
    "    var u = type === 'json' ? 'application/json' : 'text/plain',",
    "        fBlob = new Blob(dBlobs, { type: u }),",
    "        fUrl = URL.createObjectURL(fBlob),",
    "        aTag = document.createElement('a');",
    "    aTag.href = fUrl;",
    "    aTag.download = 'glyphlab_export.' + type;",
    "    aTag.click();",
    "    setTimeout(function() { URL.revokeObjectURL(fUrl); }, 10000);",
    "    isGlobalExporting = false;",
    "    if (a) a.style.display = 'none';",
    "    if (i) i.style.width = '0%';",
    "    if (s) s.innerText = '0%';",
    "    if (l) l.innerText = 'Calculating ETA...';",
    "}",
    "function dLS(idx, type) {",
    "    var c = document.getElementById('card-' + idx);",
    "    if (!c) return;",
    "    var t = c.dataset.type, b = c.dataset.block, items = JSON.parse(c.getAttribute('data-json')), hex = c.dataset.basehex, NL = String.fromCharCode(10);",
    "    if (type === 'json') {",
    "        var w = {}; w[t] = {}; w[t][b] = [items];",
    "        dL(JSON.stringify(w, null, 2), 'glyphlab_' + hex + '.json', 'application/json');",
    "    } else {",
    "        var txt = '[ ' + t + ' - ' + b + ' ]' + NL;",
    "        txt += '='.repeat(t.length + b.length + 7) + NL + NL;",
    "        txt += '=== ' + (items['CHARACTER'] || items['SYMBOL'] || '') + ' ===' + NL;",
    "        for (var k in items) txt += k + ': ' + items[k] + NL;",
    "        dL(txt, 'glyphlab_' + hex + '.txt', 'text/plain');",
    "    }",
    "}",
    "var bMap = { SINGLE: new Map(), COMBINED: new Map() }, cTab = null, activeFilters = new Set();",
    "function initF() {",
    "    bMap = { SINGLE: new Map(), COMBINED: new Map() };",
    "    document.querySelectorAll('.card').forEach(function(c) {",
    "        var t = c.dataset.type, b = c.dataset.block, i = parseInt(c.dataset.idx, 10);",
    "        if (t && bMap[t] && !bMap[t].has(b)) bMap[t].set(b, i);",
    "    });",
    "    if (bMap.SINGLE.size === 0 && bMap.COMBINED.size === 0) {",
    "        var fb = document.querySelector('.fab-filter');",
    "        if (fb) fb.style.display = 'none';",
    "        return;",
    "    }",
    "    cTab = bMap.SINGLE.size > 0 ? 'SINGLE' : 'COMBINED';",
    "    var tabsHtml = '';",
    "    if (bMap.SINGLE.size > 0) tabsHtml += '<div id=\"tb-SINGLE\" class=\"f-tab ' + (cTab === 'SINGLE' ? 'act' : '') + '\" onclick=\"setT(\\'SINGLE\\')\">SINGLE<br>CHARACTERS</div>';",
    "    if (bMap.COMBINED.size > 0) tabsHtml += '<div id=\"tb-COMBINED\" class=\"f-tab ' + (cTab === 'COMBINED' ? 'act' : '') + '\" onclick=\"setT(\\'COMBINED\\')\">COMBINED<br>CHARACTERS</div>';",
    "    var ft = document.getElementById('fTabs');",
    "    if (ft) ft.innerHTML = tabsHtml;",
    "    renderB();",
    "    filterC();",
    "}",
    "function tglM(show) {",
    "    var fo = document.getElementById('fOverlay');",
    "    if (fo) fo.style.display = show ? 'flex' : 'none';",
    "}",
    "function setT(t) {",
    "    cTab = t;",
    "    document.querySelectorAll('.f-tab').forEach(function(el) { el.classList.remove('act'); });",
    "    var tb = document.getElementById('tb-' + t);",
    "    if (tb) tb.classList.add('act');",
    "    renderB();",
    "}",
    "function renderB() {",
    "    var blocks = Array.from(bMap[cTab].entries()).map(function(e) { return { n: e[0], i: e[1] }; }).sort(function(a, b) { return a.i - b.i; });",
    "    var qEl = document.getElementById('fSearch');",
    "    var q = qEl ? qEl.value.toLowerCase().trim() : '';",
    "    var isNum = new RegExp('^[0-9]+$').test(q);",
    "    var html = '';",
    "    blocks.forEach(function(b) {",
    "        var match = false;",
    "        if (isNum) {",
    "            if (String(b.i) === q) match = true;",
    "        } else if (!q || b.n.toLowerCase().indexOf(q) !== -1) {",
    "            match = true;",
    "        }",
    "        if (match) {",
    "            var dispN = b.n;",
    "            if (!isNum && q) {",
    "                var idx = dispN.toLowerCase().indexOf(q);",
    "                dispN = dispN.substring(0, idx) + '<span class=\"hl-text\">' + dispN.substring(idx, idx + q.length) + '</span>' + dispN.substring(idx + q.length);",
    "            }",
    "            var isAct = activeFilters.has(b.n) ? 'act' : '';",
    "            var safeB = b.n.replace(/\\\\/g, \"\\\\\\\\\").replace(/'/g, \"\\\\'\");",
    "            html += '<button class=\"f-btn ' + isAct + '\" onclick=\"tglF(\\x27' + safeB + '\\x27)\"><span class=\"idx\">' + b.i + '</span>' + dispN + '</button>';",
    "        }",
    "    });",
    "    var fb = document.getElementById('fBlocks');",
    "    if (fb) fb.innerHTML = html;",
    "    var cb = document.getElementById('clearBtn');",
    "    if (cb) cb.style.display = activeFilters.size > 0 ? 'block' : 'none';",
    "}",
    "function tglF(b) {",
    "    if (activeFilters.has(b)) activeFilters.delete(b);",
    "    else activeFilters.add(b);",
    "    renderB();",
    "    filterC();",
    "}",
    "function clrF() {",
    "    activeFilters.clear();",
    "    renderB();",
    "    filterC();",
    "}",
    "function filterC() {",
    "    document.querySelectorAll('.card').forEach(function(c) {",
    "        var matchB = activeFilters.size === 0 || activeFilters.has(c.dataset.block);",
    "        c.style.display = matchB ? 'block' : 'none';",
    "    });",
    "}",
    "if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', initF); } else { initF(); }"
].join("\n");